import os
import subprocess
from pathlib import Path

TODO_PATH = Path("TODO.md")
AUTOGENERATED_TODO_HEADER = "# Autogenerated TODO. Please, dont touch it\n"

result = subprocess.run(
    [
        "git",
        "--no-pager",
        "grep",
        "-nE",
        "TODO|FIXME|HACK|XXX",
        "--",
        "src/",
    ],
    capture_output=True,
    text=True,
)

output = result.stdout
data = output.split("\n")


with TODO_PATH.open("r+") as f:
    f.seek(0)
    content = f.read()

    index = content.find(AUTOGENERATED_TODO_HEADER)

    if index == -1:
        f.seek(0, os.SEEK_END)
        f.write("\n\n")
        f.write(AUTOGENERATED_TODO_HEADER + "\n")
    else:
        next_line = content.find("\n", index) + 1
        new_content = content[:next_line]

        f.seek(0)
        f.write(new_content)
        f.truncate()

    for line in data:
        if not line:
            continue
        path, line_number, text = line.split(":", maxsplit=2)
        f.write(f"- [ ] {path}:{line_number}: {text.split('TODO:')[1].strip()}\n")
